name: Build, Deploy and Security Check

on:
  push:
    branches:
      - develop   # Trigger develop branch
      - feature/* # Trigger feature branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Build Docker image
        run: |
          docker build -t cicd-test .

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no viethq@113.160.225.29 "echo 'SSH connection successful!'"

      - name: Deploy application to server
        run: |
          ssh -o StrictHostKeyChecking=no viethq@113.160.225.29 "cd /home/viethq/cicd-test && git pull && docker-compose up -d"

      - name: Run Lynis security audit on server
        run: |
          ssh -o StrictHostKeyChecking=no viethq@113.160.225.29 "lynis audit system | tee /tmp/lynis_output.log"

      - name: Check Lynis output for issues
        run: |
          ssh -o StrictHostKeyChecking=no viethq@113.160.225.29 "if grep -q 'Warning' /tmp/lynis_output.log || grep -q 'Suggestion' /tmp/lynis_output.log; then echo 'Security issues found!'; exit 1; else echo 'No security issues detected.'; fi"

      - name: Upload Lynis report
        uses: actions/upload-artifact@v4
        with:
          name: lynis-report
          path: /tmp/lynis_output.log

      - name: Send notification if issues found
        if: failure()
        run: |
          echo "Security issues detected, sending email notification..."

